function tanc = read_trc(trial)

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/erivelton/Documents/ESC-704-Stochastic-Systems/Final-Project/propulsion raw data02/trial06/wc6.anc
%
% Auto-generated by MATLAB on 18-Mar-2021 00:15:11

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [12, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["File_Type", "AnalogRCASCII", "Var3", "Var4"];
opts.SelectedVariableNames = ["File_Type", "AnalogRCASCII"];
opts.VariableTypes = ["double", "double", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var3", "Var4"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var3", "Var4"], "EmptyFieldRule", "auto");

% Import the data
if trial < 10
    anc = readtable(append("trial0",num2str(trial),"/wc",num2str(trial),".anc"), opts);
else
    anc = readtable(append("trial",num2str(trial),"/wc",num2str(trial),".anc"), opts);
end

%% Clear temporary variables
clear opts

%%
idx = find(anc.AnalogRCASCII == 32766); 
tanc = anc.File_Type(idx);
