clear all

run('Script1_Preprocessing.m')

Mtemp = [ ...
    propulsion.IJ,	propulsion.VarName5	,	propulsion.VarName4, ...
    propulsion.PX,	propulsion.VarName8	,	propulsion.VarName7, ...
    propulsion.C7,	propulsion.VarName11,	propulsion.VarName10, ...
    propulsion.T8,	propulsion.VarName14,	propulsion.VarName13, ...
    propulsion.RAC,	propulsion.VarName17,	propulsion.VarName16, ...
    propulsion.RAS,	propulsion.VarName20,	propulsion.VarName19, ...
    propulsion.RPS,	propulsion.VarName23,	propulsion.VarName22, ...
    propulsion.RAI,	propulsion.VarName26,	propulsion.VarName25, ...
    propulsion.RPI,	propulsion.VarName29,	propulsion.VarName28, ...
    propulsion.RLE,	propulsion.VarName32,	propulsion.VarName31, ...
    propulsion.RME,	propulsion.VarName35,	propulsion.VarName34, ...
    propulsion.RRS,	propulsion.VarName38,	propulsion.VarName37, ...
    propulsion.RUS,	propulsion.VarName41,	propulsion.VarName40, ...
    propulsion.R3M,	propulsion.VarName44,	propulsion.VarName43, ...
    propulsion.R5M,	propulsion.VarName47,	propulsion.VarName46, ...
    propulsion.LAC,	propulsion.VarName50,	propulsion.VarName49, ...
    propulsion.LAS,	propulsion.VarName53,	propulsion.VarName52, ...
    propulsion.LPS,	propulsion.VarName56,	propulsion.VarName55, ...
    propulsion.LAI,	propulsion.VarName59,	propulsion.VarName58, ...
    propulsion.LPI,	propulsion.VarName62,	propulsion.VarName61, ...
    propulsion.LLE,	propulsion.VarName65,	propulsion.VarName64, ...
    propulsion.LME,	propulsion.VarName68,	propulsion.VarName67, ...
    propulsion.LRS,	propulsion.VarName71,	propulsion.VarName70, ...
    propulsion.LUS,	propulsion.VarName74,	propulsion.VarName73, ...
    propulsion.L3M,	propulsion.VarName77,	propulsion.VarName76, ...
    propulsion.L5M,	propulsion.VarName80,	propulsion.VarName79, ...
    propulsion.RW,	propulsion.VarName83,	propulsion.VarName82, ...
    propulsion.LW,	propulsion.VarName86,	propulsion.VarName85];

j = 1;
for i=1:28
    M(i).x = Mtemp(:,j); j=j+1;
    M(i).y = Mtemp(:,j); j=j+1;
    M(i).z = Mtemp(:,j); j=j+1;
end

%%
% x1 = linspace(1,10,10);
% y1 = linspace(2,11,10);
% z1 = linspace(3,12,10);
% x2 = linspace(4,13,10);
% y2 = linspace(5,14,10);
% z2 = linspace(6,15,10);
% 
% close all
% figure; hold on; plot3(x1,y1,z1); plot3(x2,y2,z2); xlabel('x');ylabel('y');zlabel('z'); view(2);
% figure; hold on; plot3(x1,y1,z1); plot3(x2,y2,z2); xlabel('x');ylabel('y');zlabel('z'); view(3);