function [M,K,kg,G,H,Q] = dyn_propulsion(A,B,Frol,Ja,Jb,Jr,R1,R2,a,ap,apdot,b,bt,btdot,gamma,gx,gy,ma,mb,mcc,mr)
%DYN_PROPULSION
%    [M,K,KG,G,H,Q] = DYN_PROPULSION(A,B,FROL,JA,JB,JR,R1,R2,A,AP,APDOT,B,BT,BTDOT,GAMMA,GX,GY,MA,MB,MCC,MR)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    02-Apr-2021 17:56:08

t2 = cos(ap);
t3 = cos(bt);
t4 = sin(ap);
t5 = sin(bt);
t6 = ap+bt;
t7 = apdot+btdot;
t8 = a.^2;
t13 = 1.0./R2;
t14 = -a;
t9 = B.*t3;
t10 = B.*t5;
t11 = cos(t6);
t12 = sin(t6);
t15 = ma.*t8;
t16 = b.*mb.*t3;
t17 = B.*a.*ma.*t2;
t20 = A+t14;
t18 = a.*t11;
t19 = a.*t12;
t22 = t11.*t14;
t23 = t12.*t14;
t24 = t2.*t20;
t25 = t4.*t20;
t29 = Ja+t15+t17;
t21 = ma.*t18;
t26 = t9+t18;
t27 = -t24;
t28 = -t25;
t30 = ma.*t26;
t31 = t16+t30;
M = reshape([ma+mb+mcc+mr+Jr.*t13.^2,t31,t21,t31,Jb+t17+t29+B.^2.*ma+b.^2.*mb,t29,t21,t29,Ja+t15],[3,3]);
if nargout > 1
    K = [-btdot.*(ma.*(btdot.*t10+t7.*t19)+b.*btdot.*mb.*t5)+apdot.*ma.*t7.*t23;B.*apdot.*ma.*t4.*t14.*(btdot+t7);B.*a.*btdot.^2.*ma.*t4];
end
if nargout > 2
    kg = [-gx.*(ma+mb+mcc+mr);-gx.*t16-gx.*t30-gy.*ma.*(t10+t19)-b.*gy.*mb.*t5;ma.*t14.*(gx.*t11+gy.*t12)];
end
if nargout > 3
    G = reshape([R1.*t13.*sin(gamma),-t9+t22+t27,t22+t27,R1.*t13.*cos(gamma),-t10+t23+t28,t23+t28],[3,2]);
end
if nargout > 4
    H = reshape([0.0,1.0,0.0,0.0,0.0,1.0],[3,2]);
end
if nargout > 5
    Q = [Frol;0.0;0.0];
end
